-- 024_member_uniqueness_and_sequential_invoices.sql
-- D1: dedupe members (keep the oldest per email/phone), then enforce
--     uniqueness with partial indexes (NULL/empty ignored).
-- A7: invoice numbers become sequential per year, generated by the
--     database instead of the client (INV-YYYY-####).

-- ---------------------------------------------------------------------------
-- 1. D1: collapse duplicate members, keeping the oldest row per key
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.collapse_member_into(
  p_dup_id UUID,
  p_keep_id UUID,
  p_keep_user_id UUID
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  -- memberships_one_active_per_member allows only one active row
  UPDATE public.memberships SET status = 'expired'
  WHERE member_id = p_dup_id AND status = 'active';

  -- invoices/payments are FK RESTRICT: re-parent before deleting
  UPDATE public.invoices SET member_id = p_keep_id WHERE member_id = p_dup_id;
  UPDATE public.payments SET member_id = p_keep_id WHERE member_id = p_dup_id;

  -- keep the duplicate's account link if the keeper has none
  IF p_keep_user_id IS NULL THEN
    UPDATE public.members SET user_id = u.user_id
    FROM (SELECT user_id FROM public.members WHERE id = p_dup_id) u
    WHERE public.members.id = p_keep_id AND u.user_id IS NOT NULL;
  END IF;

  -- memberships/check_ins/class_bookings cascade
  DELETE FROM public.members WHERE id = p_dup_id;
END $$;

DO $$
DECLARE
  group_key TEXT;
  keep_id UUID;
  keep_user_id UUID;
  dup RECORD;
BEGIN
  -- email duplicates: keep the oldest row
  FOR group_key IN
    SELECT LOWER(TRIM(email)) AS k
    FROM public.members
    WHERE email IS NOT NULL AND TRIM(email) <> ''
    GROUP BY LOWER(TRIM(email))
    HAVING COUNT(*) > 1
  LOOP
    SELECT id, user_id INTO keep_id, keep_user_id
    FROM public.members
    WHERE LOWER(TRIM(email)) = group_key
    ORDER BY created_at ASC, id ASC
    LIMIT 1;

    FOR dup IN
      SELECT id
      FROM public.members
      WHERE LOWER(TRIM(email)) = group_key
      ORDER BY created_at ASC, id ASC
      OFFSET 1
    LOOP
      RAISE NOTICE '024: collapsing member % into keeper % (email %)', dup.id, keep_id, group_key;
      PERFORM public.collapse_member_into(dup.id, keep_id, keep_user_id);
    END LOOP;
  END LOOP;

  -- phone duplicates: keep the oldest row
  FOR group_key IN
    SELECT LOWER(TRIM(phone)) AS k
    FROM public.members
    WHERE phone IS NOT NULL AND TRIM(phone) <> ''
    GROUP BY LOWER(TRIM(phone))
    HAVING COUNT(*) > 1
  LOOP
    SELECT id, user_id INTO keep_id, keep_user_id
    FROM public.members
    WHERE LOWER(TRIM(phone)) = group_key
    ORDER BY created_at ASC, id ASC
    LIMIT 1;

    FOR dup IN
      SELECT id
      FROM public.members
      WHERE LOWER(TRIM(phone)) = group_key
      ORDER BY created_at ASC, id ASC
      OFFSET 1
    LOOP
      RAISE NOTICE '024: collapsing member % into keeper % (phone %)', dup.id, keep_id, group_key;
      PERFORM public.collapse_member_into(dup.id, keep_id, keep_user_id);
    END LOOP;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- 2. D1: partial unique indexes (NULL/empty still allowed)
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS members_email_key
  ON public.members (LOWER(TRIM(email)))
  WHERE email IS NOT NULL AND TRIM(email) <> '';

CREATE UNIQUE INDEX IF NOT EXISTS members_phone_key
  ON public.members (LOWER(TRIM(phone)))
  WHERE phone IS NOT NULL AND TRIM(phone) <> '';

-- ---------------------------------------------------------------------------
-- 3. A7: sequential invoice numbers generated by the database
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.invoices_number_seq START 1;

SELECT setval(
  'public.invoices_number_seq',
  COALESCE(
    (SELECT MAX(substring(invoice_number FROM '[0-9]+$')::integer)
     FROM public.invoices
     WHERE invoice_number ~ '^INV-[0-9]{4}-[0-9]{4}$'),
    0
  ) + 1,
  false
);

CREATE OR REPLACE FUNCTION public.invoices_set_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.invoice_number := 'INV-'
    || to_char(now() AT TIME ZONE 'Asia/Manila', 'YYYY')
    || '-' || lpad(nextval('public.invoices_number_seq')::text, 4, '0');
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS invoices_sequential_number ON public.invoices;
CREATE TRIGGER invoices_sequential_number
  BEFORE INSERT ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.invoices_set_number();